Object intermediate_window_11
name intermediate_window
face intermediate_window_1.111
end
More
Object intermediate_window_12
name intermediate_window
face intermediate_window_1.111
x 1
end
Object intermediate_window_21
name intermediate_window
face intermediate_window_2.111
end

