{
  "location" : "scorn_riverside",
  "rules": [
  {
  "match" : ["mark"],
  "pre" : [],
  "post" : [],
  "msg" : ["Ya good guy lets me beat him at cards all the time.\nGuy loves to gamble.\nOtherwise he's a bum."]
  }, {
  "match" : ["amy"],
  "pre" : [],
  "post" : [],
  "msg" : ["She runs the place for that rat Witherspoon."]
  }, {
  "match" : ["Witherspoon", "rat"],
  "pre" : [],
  "post" : [],
  "msg" : ["Witherspoon owns all these slum..er 'condos'."]
  }, {
  "match" : ["gramps", "malone", "staff", "stick"],
  "pre" : [["quest", "scorn/WalkingStick", "40"]],
  "post" : [],
  "msg" : ["Ya ol Gramps Malone is right duffer.\nPlays a good game of orc knuckles.\nI think he left his walking stick here last time he came round.\nThink it's under the table..."]
  }, {
  "match" : ["gramps", "malone", "staff", "stick"],
  "pre" : [["quest", "scorn/WalkingStick", "20-30"]],
  "post" : [["quest", "scorn/WalkingStick", "40"]],
  "msg" : ["Ya ol Gramps Malone is right duffer.\nPlays a good game of orc knuckles.\nI think he left his walking stick here last time he came round.\nThink it's under the table..."]
  }, {
  "match" : ["gramps", "malone", "staff", "stick"],
  "pre" : [],
  "post" : [],
  "msg" : ["Ya ol Gramps Malone is right duffer.\nPlays a good game of orc knuckles.\nI think he left his walking stick here last time he came round.\nThink it's under the table..."]
  }, {
  "match" : ["*"],
  "pre" : [],
  "post" : [],
  "msg" : ["Darn bird keeps me awake all night..."]
  }
]}
