Object hpbar_poisoned_diseased_1
face hpbar_poisoned_diseased_1.111
end
Object hpbar_poisoned_diseased_2
face hpbar_poisoned_diseased_2.111
end
Object hpbar_poisoned_diseased_3
face hpbar_poisoned_diseased_3.111
end
Object hpbar_poisoned_diseased_4
face hpbar_poisoned_diseased_4.111
end
Object hpbar_poisoned_diseased_5
face hpbar_poisoned_diseased_5.111
end
Object hpbar_poisoned_diseased_6
face hpbar_poisoned_diseased_6.111
end
Object hpbar_poisoned_diseased_7
face hpbar_poisoned_diseased_7.111
end
Object hpbar_poisoned_diseased_8
face hpbar_poisoned_diseased_8.111
end
Object hpbar_poisoned_diseased_9
face hpbar_poisoned_diseased_9.111
end
Object hpbar_poisoned_diseased_10
face hpbar_poisoned_diseased_10.111
end
Object hpbar_poisoned_diseased_11
face hpbar_poisoned_diseased_11.111
end
Object hpbar_poisoned_diseased_12
face hpbar_poisoned_diseased_12.111
end
Object hpbar_poisoned_diseased_13
face hpbar_poisoned_diseased_13.111
end
Object hpbar_poisoned_diseased_14
face hpbar_poisoned_diseased_14.111
end
Object hpbar_poisoned_diseased_15
face hpbar_poisoned_diseased_15.111
end
Object hpbar_poisoned_diseased_16
face hpbar_poisoned_diseased_16.111
end
Object hpbar_poisoned_diseased_17
face hpbar_poisoned_diseased_17.111
end
Object hpbar_poisoned_diseased_18
face hpbar_poisoned_diseased_18.111
end
Object hpbar_poisoned_diseased_19
face hpbar_poisoned_diseased_19.111
end
Object hpbar_poisoned_diseased_20
face hpbar_poisoned_diseased_20.111
end
Object hpbar_poisoned_diseased_21
face hpbar_poisoned_diseased_21.111
end
Object hpbar_poisoned_diseased_22
face hpbar_poisoned_diseased_22.111
end
Object hpbar_poisoned_diseased_23
face hpbar_poisoned_diseased_23.111
end
Object hpbar_poisoned_diseased_24
face hpbar_poisoned_diseased_24.111
end
Object hpbar_poisoned_diseased_25
face hpbar_poisoned_diseased_25.111
end
Object hpbar_poisoned_diseased_26
face hpbar_poisoned_diseased_26.111
end
Object hpbar_poisoned_diseased_27
face hpbar_poisoned_diseased_27.111
end
Object hpbar_poisoned_diseased_28
face hpbar_poisoned_diseased_28.111
end
Object hpbar_poisoned_diseased_29
face hpbar_poisoned_diseased_29.111
end
Object hpbar_poisoned_diseased_30
face hpbar_poisoned_diseased_30.111
end
