{ "location" : "goths_hintson",
  "rules"    :
  [{ "match" : ["lowlife"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["They that ssscribblesss graffiti on ssstuff should all be ssstopped - like that cur rotting in prison."]
   },
   { "match" : ["graffiti","scribble","stuff","wall"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["Yeah, that ssscrawl on the wall over there is jussst shameful."]
   },
   { "match" : ["scrawl"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["You can't see it?  Do you need a pair of ssspectaclesss?"]
   },
   { "match" : ["cur","rotting"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["Hmmph, I told you I'm no gosssip.  Asssk him about it yerssself."]
   },
   { "match" : ["prison"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["The prison is right next door...",
                "How could ya misss it on yer way in?",
                "Itsss ssso clossse ya can hear the ruckusss through the wallsss..."]
   },
   { "match" : ["hear","ruckus"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["One inmate ssseemsss to keep the guardsss from doin' their job.",
                "The fusss is over a jailbird doesn't deserve to be there in the firsst place."]
   },
   { "match" : ["inmate","jailbird","deserve"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["Poor lasss...  and all for a look sssee...",
                "You'd think it was a peep show in there or sssomething."]
   },
   { "match" : ["look","peep","see","show"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["For shame!  Help the lasss out will ya."]
   },
   { "match" : ["help"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["Are you kidding, I would, but I'm not gonna upssset the men in mail.",
                "Jussst don't get in the guards' way..."]
   },
   { "match" : ["lass"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["She's desssperate.  Will ya help her!",
                "Has an odd name... sssomethin like hay...",
                "Don't know the name, but ya can't misss her.",
                "Jussst try not to embarrasss her more than she already is."]
   },
   { "match" : ["ask","him"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["I think his name is Eric, or sssomething like that.",
                "They all have ssstoriesss... but Eric will talk to mossst anyone..."]
   },
   { "match" : ["grifter"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["I'm no racsssissst, but that ssscaled fellow over there is a disssgrace to his race."]
   },
   { "match" : ["scaled"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["He may not be a humanoid, but he's no better than the other riff-raff hanging around town."]
   },
   { "match" : ["hanging","riff","town"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["Hey, don't take my word for it, asssk 'em what their jobsss are and you'll sssee what I mean.",
                "If they're too drunk to talk to ya, sssayin' their name might jar sssome comment loossse."]
   },
   { "match" : ["disgrace","fellow","race"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["He mussst be rolling in payola.",
                "I've never ssseen graft taken ssso blatantly and ssso frequently...",
                "As sssomeone allusss told me, 'Though the bribe be sssmall, yet the fault isss great.'"]
   },
   { "match" : ["bribe","graft","payola"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["If you don't believe me, take a ssseat; it won't be long till you sssee for yerssself what goes on..."]
   },
   { "match" : ["someone"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["Hisss name wasss Edward Coke, and thatsss all I'll tell ya."]
   },
   { "match" : ["weird"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["Ssss... he might hear you, he'sss over there... by the door... I don't think he ever sssleepsss."]
   },
   { "match" : ["door","hear","sleep"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["It'sss unreal.  I ssswear, he knowsss about every adventurer in the known world."]
   },
   { "match" : ["adventurer"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["See for yourssself... go up to him and sssay 'seen'...  Freakish, I tell you..."]
   },
   { "match" : ["sss"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["Whasssamatter? Ya got a lisssp or sssomething?"]
   },
   { "match" : ["freakish","gossip","lisp","racist"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["...sssay that again and you might be leaving with a few regretsss..."]
   },
   { "match" : ["regret"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["I'll jussst pretend I didn't hear you sssay that... thisss time...",
                "Do you regret it yet?"]
   },
   { "match" : ["name"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["Hintson... I didn't catch yours..."]
   },
   { "match" : ["hintson"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["Yeah, that'sss my name.",
                "Do me a favor... don't wear it out."]
   },
   { "match" : ["job"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["I'm on the wait-ssstaff over at the Imperial Ssstronghold.  I keep the amenity rooms ssstocked."]
   },
   { "match" : ["imperial","stronghold"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["You know... the king'sss cassstle... here in town."]
   },
   { "match" : ["amenity","privilege","room"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["Their highnesssesss reward adventurers that complete quessstsss for them with prizes and titles. They also reward men of title with sumptuous board as an ongoing token of their appreciation."]
   },
   { "match" : ["stock"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["Hey, not many people take advantage of the King's board... so itsss and easy job."]
   },
   { "match" : ["prize","quest","reward","title"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["Didn't you know?  If you sssolve a quessst for the king, you'll get a title and privilege in the landsss."]
   },
   { "match" : ["privilege"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["Freedom from this little burgh is privilege, is it not?"]
   },
   { "match" : ["*"],
     "pre"   : [],
     "post"  : [],
     "msg"   : ["You won't catch me gosssiping, but lowlifesss, griftersss and wierdosss dessserve to be ssslandered."]
   }
  ]
}

